swagger: '2.0'
info:
  version: 0.0.2
  title: Thermostat Web Gateway JVM Memory API
  license:
    name: GPL v2 with Classpath Exception
    url: 'http://www.gnu.org/licenses'
consumes:
  - application/json
produces:
  - application/json
  - text/html; charset=utf-8
basePath: /jvm-memory/0.0.2
paths:
  /:
    get:
      description: Get jvm memory information.
      parameters:
        - $ref: '#/parameters/limit'
        - $ref: '#/parameters/offset'
        - $ref: '#/parameters/sort'
        - $ref: '#/parameters/include'
        - $ref: '#/parameters/exclude'
        - $ref: '#/parameters/query'
        - $ref: '#/parameters/metadata'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/jvm-memory-stats-response'
    put:
      description: Update jvm memory information.
      parameters:
        - $ref: '#/parameters/put-body'
        - $ref: '#/parameters/query'
        - $ref: '#/parameters/metadata'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/metadata'
    post:
      description: Add jvm memory information
      parameters:
        - $ref: '#/parameters/jvm-memory-stats'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/metadata'
    delete:
      description: Delete jvm memory information.
      parameters:
        - $ref: '#/parameters/query'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/metadata'
definitions:
  jvm-memory-stats-response:
    type: object
    properties:
      response:
          $ref: '#/definitions/jvm-memory-stats'
      metadata:
        $ref: '#/definitions/metadata'
  jvm-memory-stats:
    type: array
    items:
      $ref: '#/definitions/jvm-memory-stat'
  jvm-memory-stat:
    type: object
    properties:
      agentId:
        type: string
      jvmId:
        type: string
      timeStamp:
        $ref: '#/definitions/timestamp'
      metaspaceMaxCapacity:
        $ref: '#/definitions/metric'
      metaspaceMinCapacity:
        $ref: '#/definitions/metric'
      metaspaceCapacity:
        $ref: '#/definitions/metric'
      metaspaceUsed:
        $ref: '#/definitions/metric'
      generations:
        type: array
        items:
          $ref: '#/definitions/generations-item'
  generations-item:
    type: object
    properties:
      capacity:
        $ref: '#/definitions/metric'
      collector:
        type: string
      maxCapacity:
        $ref: '#/definitions/metric'
      name:
        type: string
      spaces:
        type: array
        items:
          $ref: '#/definitions/spaces-item'
  spaces-item:
    type: object
    properties:
      capacity:
        $ref: '#/definitions/metric'
      index:
        type: integer
      maxCapacity:
        $ref: '#/definitions/metric'
      name:
        type: string
      used:
        $ref: '#/definitions/metric'
  metadata:
      type: object
      properties:
        payloadCount:
          type: integer
        count:
          type: integer
        prev:
          type: string
        next:
          type: string
        first:
          type: string
        last:
          type: string
        insertCount:
          type: integer
        matchCount:
          type: integer
        elapsed:
          type: integer
          format: int64
  metric:
    type: object
    properties:
      $numberLong:
        type: string
  timestamp:
    description: UNIX timestamp in milliseconds
    type: object
    properties:
      $numberLong:
        type: string

  put-body:
    type: object
    properties:
      "set":
        type: object
parameters:
  jvm-memory-stats:
    name: jvm-memory-stats
    in: body
    description: The jvm memory statistics
    required: true
    schema:
      $ref: '#/definitions/jvm-memory-stats'
  put-body:
    name: putBody
    in: body
    description: "The JSON object containing a 'set' object. This contains single item JSON objects that specify the field to replace and the JSON value to replace with. Example { \"set\" : { \"field\" : \"value\", \"field2\":{\"object\":\"item\"} }"
    required: true
    schema:
      $ref: '#/definitions/put-body'
  limit:
    name: limit
    in: query
    description: Limit of items to return. Example '1'
    type: integer
  offset:
    name: offset
    in: query
    description: Offset of items to return. Example '0'
    type: integer
  sort:
    name: sort
    in: query
    description: Sort string. Comma separated list of fields prefixed with '+' for ascending or '-' for descending. Example '?s=+a,-b' Fields use dot notation for embedded documents. Example 'outer.inner' refers to field inner contained in field outer.
    type: string
  query:
    name: query
    in: query
    description: Query string. Comma separated list of key, comparator, value pairs. Comparator supports '==', '<=', '>=', '<', '>', '!='. Example '?q=a==b,c!=d'. Keys are fields in documents and use dot notation for embedded documents. Example 'outer.inner' refers to field inner contained in field outer.
    type: string
  include:
    name: include
    in: query
    description: >-
      Inclusion string. Comma separated list of fields to include in the
      response. Example '?include=a,b' Fields use dot notation for embedded
      documents. Example 'outer.inner' refers to field inner contained in field
      outer. Cannot be used in combination with 'exclude' parameter. Overriden by
      'exclude' parameter
    type: string
    required: false
  exclude:
    name: exclude
    in: query
    description: >-
      Exclusion string. Comma separated list of fields to exclude in the
      response. Example '?exclude=a,b' Fields use dot notation for embedded
      documents. Example 'outer.inner' refers to field inner contained in field
      outer. Cannot be used in combination with 'include' parameter; takes
      precedence over 'include' parameter
    type: string
    required: false
  metadata:
    name: metadata
    type: boolean
    in: query
    description: "Metadata flag. If set to 'true', the subsequent request response will return metadata information. If set to 'false', such metadata information will be omitted."